# -----------------------------------------------------------------------------------------------
# Deploy Unbound DNS-over-HTTPS (DoH)
# Created by allexBR | https://github.com/allexBR
# from: https://unbound.docs.nlnetlabs.nl/en/latest/topics/privacy/dns-over-https.html#using-doh
# -----------------------------------------------------------------------------------------------

# Suggested path /etc/unbound/conf.d  or other

server:
    interface: 127.0.0.1@4443
    https-port: 4443
    http-endpoint: /dns-query
    http-notls-downstream: yes
    #tls-service-key: "/etc/unbound/unbound_server.key"
    #tls-service-pem: "/etc/unbound/unbound_server.pem"

    #http-max-streams: 100
    #http-query-buffer-size: 4m
    #http-response-buffer-size: 4m


