# -----------------------------------------------------------------------------------------------
# Deploy Unbound DNS-over-HTTPS (DoH)
# Created by allexBR | https://github.com/allexBR
# from: https://unbound.docs.nlnetlabs.nl/en/latest/topics/privacy/dns-over-https.html#using-doh
# -----------------------------------------------------------------------------------------------

tee /etc/unbound/conf.d/doh.conf <<EOF
server:
    interface: 127.0.0.1@4443
    https-port: 4443
    tls-service-key: "/etc/unbound/unbound_server.key"
    tls-service-pem: "/etc/unbound/unbound_server.pem"

    #http-endpoint: /dns-query
    #http-max-streams: 100
    #http-query-buffer-size: 4m
    #http-response-buffer-size: 4m
EOF
